# Generated by Django 4.1.2 on 2022-10-31 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kelompok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.IntegerField()),
                ('keterangan', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Mahasiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NIM', models.CharField(max_length=200)),
                ('nama', models.CharField(max_length=200)),
                ('tanggallahir', models.CharField(max_length=200)),
                ('photo', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('fakultas', models.CharField(max_length=200)),
                ('prodi', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Staf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NIP', models.CharField(max_length=200)),
                ('nama', models.CharField(max_length=200)),
                ('tanggallahir', models.CharField(max_length=200)),
                ('photo', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('unit', models.CharField(max_length=200)),
                ('alamat', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Dosen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NIP', models.CharField(max_length=200)),
                ('nama', models.CharField(max_length=200)),
                ('tanggallahir', models.DateTimeField(max_length=200)),
                ('photo', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('prodi', models.CharField(max_length=200)),
                ('alamat', models.TextField(max_length=200)),
                ('fakultas', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fakultas.kelompok')),
            ],
        ),
    ]
